- name: Install first domain controller
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install ad
      win_feature:
        name: "AD-Domain-Services"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

